limits:
  per_category: 30
  top: 25
sources:
  # ——— GENERAL / TOP ———
  - name: CoinDesk
    url: https://www.coindesk.com/arc/outboundfeeds/rss/?outputType=xml
    category: top
  - name: Cointelegraph
    url: https://cointelegraph.com/rss
    category: top
  - name: CryptoSlate
    url: https://cryptoslate.com/feed/
    category: top
  - name: Decrypt
    url: https://decrypt.co/feed
    category: top
  - name: The Block
    url: https://www.theblock.co/rss/latest
    category: top
  - name: Bitcoin Magazine
    url: https://bitcoinmagazine.com/.rss/full/
    category: top
  - name: AMBCrypto
    url: https://ambcrypto.com/feed/
    category: top
  - name: BeInCrypto
    url: https://beincrypto.com/feed/
    category: top
  - name: Daily Hodl
    url: https://dailyhodl.com/feed/
    category: top
  - name: U.Today
    url: https://u.today/rss
    category: top
  - name: NewsBTC
    url: https://www.newsbtc.com/feed/
    category: top
  - name: CryptoPotato
    url: https://cryptopotato.com/feed/
    category: top
  - name: Blockworks
    url: https://blockworks.co/feed
    category: top
  - name: Protos
    url: https://protos.com/feed/
    category: top
  - name: CoinJournal
    url: https://coinjournal.net/feed/
    category: top
  - name: Finextra
    url: https://www.finextra.com/rss/news.aspx
    category: top
  - name: Reuters Technology
    url: https://feeds.reuters.com/reuters/technologyNews
    category: top
  - name: Reuters Markets
    url: https://feeds.reuters.com/reuters/businessNews
    category: top
  - name: Yahoo Finance Crypto
    url: https://finance.yahoo.com/topic/crypto/rssindex
    category: top
  - name: Bloomberg Crypto
    url: https://www.bloomberg.com/feed/topics/crypto.xml
    category: top
  - name: Fortune Crypto
    url: https://fortune.com/crypto/feed
    category: top
  - name: Forbes Crypto
    url: https://www.forbes.com/crypto-blockchain/feed/
    category: top
  - name: CNBC Finance
    url: https://www.cnbc.com/id/100003114/device/rss/rss.html
    category: top
  - name: Ethereum World News
    url: https://ethereumworldnews.com/feed/
    category: top
  - name: Crypto Briefing
    url: https://cryptobriefing.com/feed/
    category: top
  - name: Bitcoin News
    url: https://news.bitcoin.com/feed/
    category: top
  - name: Bitcoinist
    url: https://bitcoinist.com/feed/
    category: top
  - name: CoinGape
    url: https://coingape.com/feed/
    category: top
  - name: Bankless
    url: https://www.bankless.com/feed
    category: top
  - name: Crypto News
    url: https://crypto.news/feed/
    category: top
  - name: CryptoPanic
    url: https://cryptopanic.com/rss/
    category: top
  - name: Blockonomi
    url: https://blockonomi.com/feed/
    category: top
  - name: Web3Wire
    url: https://web3wire.news/feed/
    category: top
  - name: CoinCodeCap
    url: https://coincodecap.com/feed/
    category: top
  - name: CoinLedger
    url: https://coinledger.io/feed/
    category: top
  - name: 101 Blockchains
    url: https://101blockchains.com/feed/
    category: top
  - name: Ledn
    url: https://www.ledn.io/rss
    category: top
  - name: CryptoVantage
    url: https://www.cryptovantage.com/feed/
    category: top
  # NEW: XDC-specific feed for direct updates
  - name: XinFin Blog
    url: https://medium.com/feed/xinfin
    category: top
  # NEW: Blockchain News, often covers smaller tokens
  - name: Blockchain News
    url: https://blockchain.news/rss
    category: top
  # ——— REGULATION & POLICY ———
  - name: SEC Press
    url: https://www.sec.gov/news/pressreleases.rss
    category: regulation
  - name: CFTC Press
    url: https://www.cftc.gov/PressRoom/PressReleases/rss
    category: regulation
  - name: US Treasury
    url: https://home.treasury.gov/news/press-releases/feed
    category: regulation
  - name: Federal Reserve
    url: https://www.federalreserve.gov/feeds/press_all.xml
    category: regulation
  - name: IMF Blog
    url: https://blogs.imf.org/feed/
    category: regulation
  - name: BIS Press
    url: https://www.bis.org/list/press_releases.rss
    category: regulation
  - name: World Bank Blogs
    url: https://blogs.worldbank.org/feed
    category: regulation
  - name: Reuters Financial Regulation
    url: https://feeds.reuters.com/reuters/financialRegulatory
    category: regulation
  - name: Politico Finance
    url: https://www.politico.com/rss/politics08.xml
    category: regulation
  - name: FT Alphaville
    url: https://ftalphaville.ft.com/feed/
    category: regulation
  - name: CoinDesk Regulation
    url: https://www.coindesk.com/policy/rss/
    category: regulation
  - name: The Block Regulation
    url: https://www.theblock.co/rss/regulation
    category: regulation
  - name: Decrypt Regulation
    url: https://decrypt.co/feed
    category: regulation
  # ——— TOKENIZATION / RWAs ———
  - name: R3 Blog
    url: https://www.r3.com/feed/
    category: tokenization
  - name: DTCC News
    url: https://www.dtcc.com/news/atom
    category: tokenization
  - name: Securitize
    url: https://securitize.io/blog/rss.xml
    category: tokenization
  - name: Tokeny
    url: https://blog.tokeny.com/rss.xml
    category: tokenization
  - name: Ondo Finance
    url: https://blog.ondo.finance/feed
    category: tokenization
  - name: Franklin Templeton Digital Assets
    url: https://digitalassets.franklintempleton.com/feed/
    category: tokenization
  - name: Hamilton Lane
    url: https://www.hamiltonlane.com/en-US/rss
    category: tokenization
  - name: Deloitte FS
    url: https://www2.deloitte.com/global/en/insights/industry/financial-services.rss.html
    category: tokenization
  - name: PwC
    url: https://www.pwc.com/gx/en/industries/financial-services/assets.rss
    category: tokenization
  - name: EY Global Finance
    url: https://www.ey.com/en_gl/rss
    category: tokenization
  - name: BCG Insights
    url: https://www.bcg.com/insights/rss
    category: tokenization
  - name: Accenture Blockchain
    url: https://www.accenture.com/us-en/insights/blockchain/_jcr_content/root/responsivegrid/feed.xml
    category: tokenization
  # ——— RESEARCH / DATA ———
  - name: Messari Research
    url: https://messari.io/rss
    category: research
  - name: Glassnode Insights
    url: https://insights.glassnode.com/rss/
    category: research
  - name: Coin Metrics
    url: https://coinmetrics.io/feed/
    category: research
  - name: Nansen Blog
    url: https://www.nansen.ai/blog/rss.xml
    category: research
  - name: Kaiko Research
    url: https://www.kaiko.com/feed
    category: research
  - name: Chainalysis Blog
    url: https://blog.chainalysis.com/feed/
    category: research
  - name: IntoTheBlock
    url: https://blog.intotheblock.com/feed
    category: research
  - name: TokenTerminal
    url: https://tokenterminal.com/feed
    category: research
  - name: Santiment Insights
    url: https://insights.santiment.net/feed
    category: research
  - name: CryptoQuant Blog
    url: https://cryptoquant.com/blog/feed
    category: research
  - name: Ark Invest
    url: https://ark-invest.com/feed/
    category: research
  # ——— CULTURE / COMMENTARY ———
  - name: Bankless
    url: https://www.bankless.com/feed
    category: culture
  - name: The Defiant
    url: https://thedefiant.io/feed
    category: culture
  - name: Unchained
    url: https://unchainedcrypto.com/feed/
    category: culture
  - name: Coin Bureau
    url: https://www.coinbureau.com/feed/
    category: culture
  - name: CoinDesk Opinion
    url: https://www.coindesk.com/opinion/rss
    category: culture
  - name: BTC Times
    url: https://www.btctimes.com/rss
    category: culture
  # ——— MARKETS ———
  - name: CoinDesk Markets
    url: https://www.coindesk.com/markets/rss/
    category: markets
  - name: Cointelegraph Markets
    url: https://cointelegraph.com/tags/markets/rss
    category: markets
  - name: Investing.com Crypto
    url: https://www.investing.com/rss/news_301.rss
    category: markets
  - name: FXStreet Crypto
    url: https://www.fxstreet.com/rss/cryptocurrencies
    category: markets
  - name: MarketWatch Crypto
    url: https://www.marketwatch.com/rss/crypto
    category: markets
  - name: Nasdaq Digital Assets
    url: https://www.nasdaq.com/feed/rssoutbound
    category: markets
  - name: CoinMarketCap Blog
    url: https://blog.coinmarketcap.com/feed/
    category: markets
  - name: CoinGecko Blog
    url: https://blog.coingecko.com/rss/
    category: markets
x_accounts:
  # Keep existing accounts, no changes needed since @XinFin_Official and @Zebec_HQ are included
  # Removed duplicates for brevity; ensure no repeats in actual file
  - name: CoinDesk
    handle: CoinDesk
  - name: Cointelegraph
    handle: Cointelegraph
  - name: TheBlock
    handle: TheBlock__
  - name: Decrypt
    handle: decryptmedia
  - name: Bankless
    handle: BanklessHQ
  - name: DefiantNews
    handle: DefiantNews
  - name: Chainlink
    handle: chainlink
  - name: OndoFinance
    handle: OndoFinance
  - name: RWA_xyz
    handle: RWA_xyz
  - name: DanTapiero
    handle: DTAPCAP
  - name: CamilaRusso
    handle: CamiRusso
  - name: CathieWood
    handle: CathieDWood
  - name: CZBinance
    handle: cz_binance
  - name: VitalikButerin
    handle: VitalikButerin
  - name: Ripple
    handle: Ripple
  - name: Hedera
    handle: hedera
  - name: StellarOrg
    handle: StellarOrg
  - name: RealVisionCrypto
    handle: RealVisionCrypto
  - name: MessariCrypto
    handle: MessariCrypto
  - name: Centrifuge
    handle: centrifuge_io
  - name: BlackRock
    handle: BlackRock
  - name: GaryGensler
    handle: GaryGensler
  - name: CryptoLawUS
    handle: CryptoLawUS
  - name: TokenizedHQ
    handle: TokenizedHQ
  - name: MichaelSaylor
    handle: saylor
  - name: AnthonyPompliano
    handle: APompliano
  - name: LarkDavis
    handle: TheCryptoLark
  - name: BitBoyCrypto
    handle: BitBoy_Crypto
  - name: CharlieLee
    handle: SatoshiLite
  - name: BalajiSrinivasan
    handle: balajis
  - name: ElonMusk
    handle: elonmusk
  - name: ErikVoorhees
    handle: ErikVoorhees
  - name: RogerVer
    handle: rogerkver
  - name: ChrisDixon
    handle: cdixon
  - name: MarcAndreessen
    handle: pmarca
  - name: JustinSun
    handle: justinsuntron
  - name: MuradMahmudov
    handle: MustStopMurad
  - name: CarlRunefelt
    handle: TheMoonCarl
  - name: AndreasAntonopoulos
    handle: aantonop
  - name: RanNeuner
    handle: cryptomanran
  - name: NatalieBrunell
    handle: natbrunell
  - name: AlexGladstein
    handle: gladstein
  - name: NicCarter
    handle: nic__carter
  - name: PeterMcCormack
    handle: PeterMcCormack
  - name: CoinMarketCap
    handle: CoinMarketCap
  - name: Binance
    handle: binance
  - name: Ethereum
    handle: ethereum
  - name: BitcoinMagazine
    handle: BitcoinMagazine
  - name: Solana
    handle: solana
  - name: Cardano
    handle: Cardano
  - name: Polkadot
    handle: Polkadot
  - name: Avalanche
    handle: avax
  - name: RWAInc
    handle: RWA_Inc_
  - name: RWAWatchlist
    handle: RWAwatchlist_
  - name: Securitize
    handle: Securitize
  - name: DaanCrypto
    handle: DaanCrypto
  - name: CryptoRover
    handle: rovercrc
  - name: AshCrypto
    handle: Ashcryptoreal
  - name: IlCapoOfCrypto
    handle: CryptoCapo_
  - name: MichaelVanDePoppe
    handle: CryptoMichNL
  - name: CryptoSlate
    handle: CryptoSlate
  - name: CoinBureau
    handle: CoinBureau
  - name: Glassnode
    handle: glassnode
  - name: Chainalysis
    handle: chainalysis
  - name: KaikoData
    handle: KaikoData
  - name: ArkhamIntel
    handle: arkhamintel
  - name: NansenAI
    handle: nansen_ai
  - name: DuneAnalytics
    handle: dune
  - name: Coinbase
    handle: coinbase
  - name: KrakenFX
    handle: krakenfx
  - name: FlareNetwork
    handle: FlareNetworks
  - name: XinFin_Official
    handle: XinFin_Official
  - name: HederaHashgraph
    handle: hedera
  - name: ZebecProtocol
    handle: Zebec_HQ
  - name: SongbirdSGB
    handle: SongbirdSGB
  - name: BradGarlinghouse
    handle: bgarlinghouse
  - name: DavidSchwartz
    handle: JoelKatz
  - name: CharlesHoskinson
    handle: IOHK_Charles
  - name: GavinWood
    handle: gavofyork
  - name: AnatolyYakovenko
    handle: aeyakovenko
  - name: SergeyNazarov
    handle: SergeyNazarov
  - name: JedMcCaleb
    handle: JedMcCaleb
  - name: LeemonBaird
    handle: leemonbaird
  - name: BinanceCoin
    handle: binance
  - name: Tether
    handle: Tether_to
  - name: USDC
    handle: circle
  - name: Dogecoin
    handle: dogecoin
  - name: Toncoin
    handle: ton_blockchain
  - name: Tron
    handle: TronDAO
  - name: Polygon
    handle: 0xPolygon
  - name: Litecoin
    handle: litecoin
  - name: NearProtocol
    handle: nearprotocol
  - name: Uniswap
    handle: Uniswap
  - name: Pepe
    handle: pepecoineth
  - name: InternetComputer
    handle: dfnity
  - name: Leo
    handle: bitfinex
  - name: Dai
    handle: MakerDAO
  - name: Aptos
    handle: Aptos_Network
  - name: EthereumClassic
    handle: eth_classic
  - name: Stacks
    handle: Stacks
  - name: Filecoin
    handle: Filecoin
  - name: Bittensor
    handle: Bittensor_
  - name: Cosmos
    handle: cosmos
  - name: Cronos
    handle: cryptocom
  - name: Immutable
    handle: Immutable
  - name: Mantle
    handle: mantle
  - name: Stellar
    handle: StellarOrg
  - name: Arbitrum
    handle: Arbitrum
  - name: Render
    handle: render_network
  - name: VeChain
    handle: vechainofficial
  - name: Okb
    handle: OKX
  - name: Maker
    handle: MakerDAO
  - name: Injective
    handle: Injective_
  - name: TheGraph
    handle: graphprotocol
  - name: Optimism
    handle: optimism
  - name: Arweave
    handle: ArweaveTeam
  - name: Sui
    handle: SuiNetwork
  - name: Monero
    handle: monero
  - name: FLOKI
    handle: RealFlokiInu
  - name: Theta
    handle: Theta_Network
  - name: Fantom
    handle: FantomFDN
  - name: THORChain
    handle: THORChain
  - name: RocketPool
    handle: Rocket_Pool
  - name: Fetch.ai
    handle: fetch_ai
  - name: LidoDAO
    handle: LidoFinance
  - name: Celestia
    handle: CelestiaOrg
  - name: Algorand
    handle: Algorand
  - name: Gala
    handle: GoGalaGames
  - name: BitgetToken
    handle: bitgetglobal
  - name: Sei
    handle: SeiNetwork
  - name: Quant
    handle: QuantHQ
  - name: Flow
    handle: flow_blockchain
  - name: Beam
    handle: Onbeam
  - name: BitcoinSV
    handle: BitcoinSV
  - name: Aave
    handle: AaveAave
  - name: BitTorrent
    handle: BitTorrent
  - name: Chiliz
    handle: Chiliz
  - name: dYdX
    handle: dydx
  - name: Neo
    handle: Neo_Blockchain
  - name: AkashNetwork
    handle: AkashNW
  - name: SingularityNET
    handle: SingularityNET
  - name: MultiversX
    handle: MultiversX
  - name: AxieInfinity
    handle: AxieInfinity
  - name: Pendle
    handle: pendle_fi
  - name: SandBox
    handle: TheSandboxGame
  - name: Tezos
    handle: Tezos
  - name: eCash
    handle: ecashofficial
  - name: Gnosis
    handle: gnosisPM
  - name: Conflux
    handle: Conflux_Network
  - name: Decentraland
    handle: decentraland
  - name: EOS
    handle: EOSNetworkFDN
  - name: Nexo
    handle: Nexo
  - name: Ronin
    handle: Ronin_Network
  - name: Oasis
    handle: OasisProtocol
  - name: GateToken
    handle: gate_io
  - name: IOTA
    handle: iota
  - name: Kava
    handle: KavaPlatform
  - name: NervosNetwork
    handle: NervosNetwork
  - name: USDD
    handle: usddio
  - name: PancakeSwap
    handle: PancakeSwap
  - name: Synthetix
    handle: synthetixtalk
  - name: ThetaFuel
    handle: Theta_Network
  - name: Klaytn
    handle: klaytn_official
  - name: Livepeer
    handle: Livepeer
  - name: Helium
    handle: helium
  - name: BitcoinGold
    handle: bitcoingold
  - name: CurveDAO
    handle: CurveFinance
  - name: Osmosis
    handle: osmosiszone
  - name: Blur
    handle: blur_io
  - name: EnjinCoin
    handle: enjin
  - name: WOO
    handle: WooNetwork
  - name: Compound
    handle: compoundfinance
  - name: Kusama
    handle: kusamanetwork
  - name: Amp
    handle: ampleforth
  - name: JUST
    handle: defi_just
  - name: 1inch
    handle: 1inch
  - name: Dash
    handle: Dashpay
  - name: MaskNetwork
    handle: realmasknetwork
  - name: Loopring
    handle: loopringorg
  - name: Ankr
    handle: ankr
  - name: TerraClassic
    handle: terra_money
  - name: BasicAttentionToken
    handle: BATproject
  - name: aelf
    handle: aelfblockchain
  - name: Moonbeam
    handle: moonbeamnetwork
  - name: Qtum
    handle: qtum
  - name: ConvexFinance
    handle: ConvexFinance
  - name: STEPN
    handle: Stepnofficial
  - name: Waves
    handle: WavesProtocol
  - name: Harmony
    handle: harmonyprotocol
  - name: Kadena
    handle: Kadena_io
  - name: Siacoin
    handle: SiaTechHQ
  - name: ICON
    handle: helloiconworld
  - name: Decred
    handle: decredproject
  - name: yearn.finance
    handle: yearnfi
  - name: Storj
    handle: storj
  - name: Ontology
    handle: OntologyNetwork
  - name: Balancer
    handle: Balancer
  - name: BandProtocol
    handle: BandProtocol
  - name: KyberNetwork
    handle: KyberNetwork
  - name: Cartesi
    handle: cartesi
  - name: Numeraire
    handle: numerai
  - name: iExecRLC
    handle: iEx_ec
  - name: CelerNetwork
    handle: CelerNetwork
  - name: Radicle
    handle: radicle
  - name: Audius
    handle: Audius
  - name: KeepNetwork
    handle: keep_project
  - name: Orchid
    handle: OrchidOfficial
  - name: PowerLedger
    handle: PowerLedger
  - name: Request
    handle: RequestNetwork
  - name: OceanProtocol
    handle: oceanprotocol
  - name: Augur
    handle: AugurProject
  - name: Status
    handle: ethstatus
  - name: Aragon
    handle: AragonProject
  - name: Civic
    handle: civicteam
  - name: district0x
    handle: district0x
  - name: Bancor
    handle: Bancor
  - name: GnosisSafe
    handle: gnosisSafe
  - name: 0xProtocol
    handle: 0xProject
  - name: Ren
    handle: RepublicProtocol
  - name: Polymath
    handle: PolymathNetwork
  - name: RaidenNetwork
    handle: raiden_network
  - name: Melon
    handle: enzyme_finance
  - name: FunFair
    handle: FunFairTech
  - name: Salt
    handle: SALTLending
  - name: Wings
    handle: Wingsplatform
  - name: Humaniq
    handle: Humaniq_co
  - name: Mysterium
    handle: MysteriumNet
  - name: Metal
    handle: MetalPay
  - name: Edgeless
    handle: EdgelessCasino
  - name: SwarmCity
    handle: SwarmCity
  - name: FirstBlood
    handle: 1stBloodio
  - name: Golem
    handle: golemproject
  - name: SingularDTV
    handle: SingularDTV
  - name: vSlice
    handle: vDice_io
  - name: DigixDAO
    handle: DigixGlobal
  - name: ICONOMI
    handle: iconomifunds
  - name: Lisk
    handle: LiskHQ
  - name: WavesPlatform
    handle: WavesProtocol
  - name: GameCredits
    handle: gamecredits
  - name: BitShares
    handle: BitSharesUI
  - name: NXT
    handle: NxtCommunity
  - name: Peercoin
    handle: PeercoinNet
  - name: Namecoin
    handle: namecoin
  - name: Primecoin
    handle: primecoin
  - name: Feathercoin
    handle: Feathercoin
  - name: Terracoin
    handle: terracoin
  - name: Freicoin
    handle: freicoin
  - name: Litecoin
    handle: litecoin
  - name: Bitcoin
    handle: Bitcoin
  - name: Dogecoin
    handle: dogecoin
